import { isBeforeISO, type ISODate } from "@/lib/date";

import { occursOn, parseRRule } from "./recurrence";

/**
 * Compose the day plan from task definitions + legacy completions + occurrence overrides.
 *
 * occurrence_date is the immutable source identity from the recurring series.
 * scheduled_date is the actual day where the occurrence is shown after a one-off move.
 * Multiple source occurrences may therefore share one scheduled_date.
 */
export type PlanTask = {
  id: string;
  title: string;
  domain: string;
  due_date: string | null;
  recurrence_rule: string | null;
  completed_at: string | null;
  goal_id: string | null;
  goal?: { id: string; title: string } | null;
};

export type PlanCompletion = { task_id: string; completed_on: string };

export type PlanOccurrence = {
  id?: string;
  task_id: string;
  /** Immutable source date generated by the series. */
  occurrence_date: string;
  /** Actual display date after a one-off move. Older rows may omit it during transition. */
  scheduled_date?: string | null;
  status: "planned" | "completed" | "skipped" | "archived" | string;
};

export type DayTaskItem<T extends PlanTask = PlanTask> = {
  /** Unique per task occurrence, including when two occurrences land on the same day. */
  key: string;
  task: T;
  /** Actual day this item is displayed/scheduled. */
  date: ISODate;
  /** Immutable source date for recurring occurrence actions. */
  occurrenceDate?: ISODate;
  occurrenceId?: string | null;
  done: boolean;
  overdue: boolean;
  recurring: boolean;
  /** false for a series-definition row shown on a day where no occurrence exists. */
  actionable?: boolean;
  skipped?: boolean;
};

export type DayPlan<T extends PlanTask = PlanTask> = {
  date: ISODate;
  overdue: DayTaskItem<T>[];
  due: DayTaskItem<T>[];
  done: DayTaskItem<T>[];
};

function scheduledDate(occurrence: PlanOccurrence): ISODate {
  return (occurrence.scheduled_date ?? occurrence.occurrence_date) as ISODate;
}

function recurringItem<T extends PlanTask>(
  task: T,
  occurrence: PlanOccurrence | null,
  displayDate: ISODate,
  sourceDate: ISODate,
  legacyCompleted: boolean,
): DayTaskItem<T> {
  const status = occurrence?.status;
  const skipped = status === "skipped" || status === "archived";
  return {
    key: `${task.id}:${sourceDate}`,
    task,
    date: displayDate,
    occurrenceDate: sourceDate,
    occurrenceId: occurrence?.id ?? null,
    done: status === "completed" || (!occurrence && legacyCompleted),
    overdue: false,
    recurring: true,
    skipped,
  };
}

export function itemsForDate<T extends PlanTask>(
  tasks: T[],
  completions: PlanCompletion[],
  date: ISODate,
  occurrences: PlanOccurrence[] = [],
): DayTaskItem<T>[] {
  const completedOn = new Set(
    completions.filter((c) => c.completed_on === date).map((c) => c.task_id),
  );
  const occurrencesByTask = new Map<string, PlanOccurrence[]>();
  for (const occurrence of occurrences) {
    const list = occurrencesByTask.get(occurrence.task_id) ?? [];
    list.push(occurrence);
    occurrencesByTask.set(occurrence.task_id, list);
  }

  const items: DayTaskItem<T>[] = [];

  for (const task of tasks) {
    if (!task.due_date) continue;
    const rule = parseRRule(task.recurrence_rule);

    if (!rule) {
      if (task.due_date === date) {
        items.push({
          key: task.id,
          task,
          date,
          done: task.completed_at !== null,
          overdue: false,
          recurring: false,
        });
      }
      continue;
    }

    const taskOccurrences = occurrencesByTask.get(task.id) ?? [];

    // The natural series occurrence for this date. A source override can move it
    // away, complete it, or skip it without mutating the recurring definition.
    if (occursOn(rule, task.due_date, date)) {
      const sourceOverride = taskOccurrences.find(
        (occurrence) => occurrence.occurrence_date === date,
      );
      if (!sourceOverride) {
        items.push(recurringItem(task, null, date, date, completedOn.has(task.id)));
      } else if (scheduledDate(sourceOverride) === date) {
        items.push(
          recurringItem(task, sourceOverride, date, date, completedOn.has(task.id)),
        );
      }
      // If scheduled_date differs, this source occurrence was moved elsewhere,
      // so the natural slot on this date is intentionally suppressed.
    }

    // A moved occurrence from another source date can coexist with the natural
    // occurrence above. This is essential for DAILY rules where moving today to
    // tomorrow must not erase tomorrow's own occurrence.
    for (const occurrence of taskOccurrences) {
      const sourceDate = occurrence.occurrence_date as ISODate;
      if (sourceDate === date || scheduledDate(occurrence) !== date) continue;
      items.push(recurringItem(task, occurrence, date, sourceDate, false));
    }
  }

  return items;
}

/** One-off tasks that are overdue before today. Recurring routines do not roll over. */
export function overdueItems<T extends PlanTask>(tasks: T[], today: ISODate): DayTaskItem<T>[] {
  return tasks
    .filter(
      (t) =>
        t.recurrence_rule === null &&
        t.due_date !== null &&
        t.completed_at === null &&
        isBeforeISO(t.due_date, today),
    )
    .sort((a, b) => a.due_date!.localeCompare(b.due_date!))
    .map((task) => ({
      key: task.id,
      task,
      date: task.due_date!,
      done: false,
      overdue: true,
      recurring: false,
    }));
}

export function buildDayPlan<T extends PlanTask>(
  tasks: T[],
  completions: PlanCompletion[],
  date: ISODate,
  today: ISODate,
  occurrences: PlanOccurrence[] = [],
): DayPlan<T> {
  const items = itemsForDate(tasks, completions, date, occurrences);
  return {
    date,
    overdue: date === today ? overdueItems(tasks, today) : [],
    due: items.filter((i) => !i.done && !i.skipped),
    done: items.filter((i) => i.done || i.skipped),
  };
}

/**
 * Tasks for a goal detail. Recurring definitions show today's occurrence state.
 * If multiple source occurrences are scheduled today, each is represented.
 */
export function goalTaskItems<T extends PlanTask>(
  tasks: T[],
  completions: PlanCompletion[],
  today: ISODate,
  occurrences: PlanOccurrence[] = [],
): DayTaskItem<T>[] {
  const result: DayTaskItem<T>[] = [];

  for (const task of tasks) {
    if (task.recurrence_rule) {
      const todayItems = itemsForDate([task], completions, today, occurrences);
      if (todayItems.length > 0) {
        result.push(...todayItems);
      } else {
        const sourceOverride = occurrences.find(
          (occurrence) =>
            occurrence.task_id === task.id && occurrence.occurrence_date === today,
        );
        const movedAway =
          sourceOverride != null && scheduledDate(sourceOverride) !== today;

        // A moved source occurrence must stay absent from its old day. When today
        // is not an occurrence day at all, keep the historical series-definition
        // row in Goal Detail so the recurring task remains discoverable/editable.
        if (!movedAway) {
          result.push({
            key: `${task.id}:${today}`,
            task,
            date: today,
            occurrenceDate: today,
            done: false,
            overdue: false,
            recurring: true,
            actionable: false,
          });
        }
      }
      continue;
    }

    const date = (task.due_date ?? today) as ISODate;
    const done = task.completed_at !== null;
    result.push({
      key: task.id,
      task,
      date,
      done,
      overdue: !done && task.due_date !== null && isBeforeISO(task.due_date, today),
      recurring: false,
    });
  }

  return result;
}
