-- Kemtit V2 recurring occurrence identity correction.
-- occurrence_date is the immutable identity of the occurrence in the RRULE series.
-- scheduled_date is where that occurrence is currently shown after a one-off move.
-- This lets a moved occurrence coexist with the series occurrence that naturally falls on the same day.

alter table public.task_occurrences
  add column if not exists scheduled_date date;

update public.task_occurrences
set scheduled_date = occurrence_date
where scheduled_date is null;

alter table public.task_occurrences
  alter column scheduled_date set not null;

create index if not exists task_occurrences_user_scheduled_date_idx
  on public.task_occurrences (user_id, scheduled_date, status);

create index if not exists task_occurrences_task_scheduled_date_idx
  on public.task_occurrences (task_id, scheduled_date);

comment on column public.task_occurrences.occurrence_date is
  'Immutable source date generated by the recurring series; identity is unique per task + source date.';

comment on column public.task_occurrences.scheduled_date is
  'Actual date where this occurrence is displayed after a one-off reschedule. Defaults to the source occurrence date.';

-- Keep the migration safe for an older application binary during rolling deploys:
-- old writes omit scheduled_date, so the ownership trigger fills the source date.
create or replace function public.task_occurrences_check_task_owner()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.scheduled_date is null then
    new.scheduled_date = new.occurrence_date;
  end if;

  if not exists (
    select 1
    from public.tasks t
    where t.id = new.task_id
      and t.user_id = new.user_id
  ) then
    raise exception 'task occurrence must belong to the same user' using errcode = '23514';
  end if;

  return new;
end
$$;

create or replace function public.reschedule_task_occurrence_atomic(
  p_task_id uuid,
  p_occurrence_date date,
  p_new_occurrence_date date
)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_id uuid;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.tasks t
    where t.id = p_task_id
      and t.user_id = v_user_id
      and t.recurrence_rule is not null
      and t.archived_at is null
      and t.deleted_at is null
  ) then
    raise exception 'recurring task not found' using errcode = 'P0002';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_task_id::text, 0));

  insert into public.task_occurrences (
    task_id,
    user_id,
    occurrence_date,
    scheduled_date,
    status,
    completed_at,
    skipped_at
  )
  values (
    p_task_id,
    v_user_id,
    p_occurrence_date,
    p_new_occurrence_date,
    'planned',
    null,
    null
  )
  on conflict (task_id, occurrence_date) do update
    set scheduled_date = excluded.scheduled_date,
        status = 'planned',
        completed_at = null,
        skipped_at = null
  returning id into v_id;

  return v_id;
end
$$;

revoke all on function public.reschedule_task_occurrence_atomic(uuid, date, date) from public;
revoke all on function public.reschedule_task_occurrence_atomic(uuid, date, date) from anon;
grant execute on function public.reschedule_task_occurrence_atomic(uuid, date, date) to authenticated;

-- Strengthen TimeBlock -> occurrence integrity while preserving task-only blocks.
create or replace function public.time_blocks_check_task_owner()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_occurrence_task_id uuid;
begin
  if new.task_id is not null
     and not exists (
       select 1
       from public.tasks t
       where t.id = new.task_id
         and t.user_id = new.user_id
     ) then
    raise exception 'time block task must belong to the same user' using errcode = '23514';
  end if;

  if new.task_occurrence_id is not null then
    select o.task_id
      into v_occurrence_task_id
    from public.task_occurrences o
    where o.id = new.task_occurrence_id
      and o.user_id = new.user_id;

    if v_occurrence_task_id is null then
      raise exception 'time block occurrence must belong to the same user' using errcode = '23514';
    end if;

    if new.task_id is null then
      new.task_id = v_occurrence_task_id;
    elsif new.task_id <> v_occurrence_task_id then
      raise exception 'time block task and occurrence must refer to the same task' using errcode = '23514';
    end if;
  end if;

  return new;
end
$$;
