-- goal_entries: บันทึกยอดรายวันของ metric goal (Claude Design turn 6/7 "บันทึกยอด")
-- goals.current_value กลายเป็นค่าที่คำนวณจาก sum(amount) ผ่าน trigger — โค้ด progress เดิมไม่ต้องแก้
create table public.goal_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  goal_id uuid not null references public.goals (id) on delete cascade,
  entry_no bigint generated by default as identity,
  entry_date date not null,
  amount numeric not null check (amount <> 0),
  note text check (note is null or char_length(note) between 1 and 120),
  channel text check (channel is null or channel in ('shopee','lazada','tiktok','line','facebook','storefront','other')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.goal_entries is 'บันทึกยอดของ metric goal (append-only + แก้/ลบได้) — goals.current_value = greatest(0, sum(amount)) ผ่าน trigger';
create index goal_entries_goal_date_idx on public.goal_entries (goal_id, entry_date desc, created_at desc);
create index goal_entries_user_date_idx on public.goal_entries (user_id, entry_date desc);
create trigger set_goal_entries_updated_at before update on public.goal_entries for each row execute function public.set_updated_at();

-- แถวต้องผูก goal ของ user เดียวกันและเป็น metric goal เท่านั้น (แบบเดียวกับ goal_photos_check_goal_owner) + ห้ามย้าย goal_id ตอนแก้
create function public.goal_entries_check_goal_owner()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' then
    if new.goal_id <> old.goal_id then
      raise exception 'cannot move an entry to a different goal' using errcode = '23514';
    end if;
  end if;
  if not exists (
    select 1 from public.goals g
    where g.id = new.goal_id and g.user_id = new.user_id and g.goal_kind = 'metric'
  ) then
    raise exception 'goal must belong to the same user and be a metric goal' using errcode = '23514';
  end if;
  return new;
end
$$;
create trigger goal_entries_goal_owner
  before insert or update on public.goal_entries
  for each row execute function public.goal_entries_check_goal_owner();

-- sync trigger: goals.current_value = greatest(0, sum(amount)) ของ goal นั้นเสมอ — ทำงานหลัง insert/update/delete แถวใดก็ตาม
-- ไม่ใช่ security definer: รันด้วยสิทธิ์ผู้เรียก (เจ้าของ goal) → policy "goals: update own" อนุญาตอยู่แล้ว
create function public.goal_entries_sync_goal()
returns trigger
language plpgsql
as $$
declare
  v_goal uuid := coalesce(new.goal_id, old.goal_id);
begin
  update public.goals
  set current_value = greatest(0, coalesce((select sum(amount) from public.goal_entries where goal_id = v_goal), 0))
  where id = v_goal;
  return null;
end
$$;
create trigger goal_entries_sync_goal
  after insert or update or delete on public.goal_entries
  for each row execute function public.goal_entries_sync_goal();

-- ---------- RLS ----------
alter table public.goal_entries enable row level security;

create policy "goal_entries: select own" on public.goal_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy "goal_entries: insert own" on public.goal_entries for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "goal_entries: update own" on public.goal_entries for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "goal_entries: delete own" on public.goal_entries for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.goal_entries from anon;

-- ---------- backfill: current_value เดิมของ metric goal กลายเป็นแถวเริ่มต้น 1 แถว (trigger sync จะคำนวณ current_value กลับมาเท่าเดิม) ----------
insert into public.goal_entries (user_id, goal_id, entry_date, amount, note)
select user_id, id, (created_at at time zone 'Asia/Bangkok')::date, current_value, 'ยอดเริ่มต้น'
from public.goals
where goal_kind = 'metric' and current_value > 0;
